# Exercise 1: Introduction to Python

### Use Python as a calculator to compute 256²

In [2]:
256**2

65536

### Put the strings "Hello" and "World!" in two variables. Concatenate both Strings and print them

In [1]:
print('Hello' + ' World!')

HelloWorld


### Create a list that contains the 4 strings "alpha", "beta", "gamma", and "delta". Add "epsilon" to the end of this list

In [4]:
list = ['alpha','beta','gamma','delta']
list.append('epsilon')
print(list)

['alpha', 'beta', 'gamma', 'delta', 'epsilon']


### Create a sublist with the first three elements of this list


In [9]:
sublist = list[:3]
print(sublist)

['alpha', 'beta', 'gamma']


### Write a Python program to construct the following pattern using for loops

In [ ]:
* 
* * 
* * * 
* * * * 
* * * * * 
* * * * 
* * * 
* * 
*

In [66]:
a = ['* ','* ','* ','* ','* ']
j = 1
for i in a:
    print(i*j)
    j = j+1

for i in a:
    print(i*len(a))
    a=a[:-1]

* 
* * 
* * * 
* * * * 
* * * * * 
* * * * * 
* * * * 
* * * 
* * 
* 


### Write a function that takes 3 input parameters and returns the product of these values

In [22]:
def fun_product(a,b,c):
    return a*b*c
print(fun_product(1,2,3))

6


### Write a Python function that takes an int as a parameter and checks if the number is prime or not.

In [1]:
def fun_check(temp):
    return temp == 7
x = int(input())
print(fun_check(x))

7
True


### Use your function to create a list that contains all primes from 2 to 100

In [37]:
num=[];
i=2
for i in range(2,100):
   j=2
   for j in range(2,i):
      if(i%j==0):
         break
   else:
      num.append(i)
print(num)

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]


### Write a function that simulates dice rolls (6-sided dices)
- Write a function that has the number of dice rolls as the input parameter
- The output is a map with the counts how often each result of a roll (1-6) occurred
- You can use the randomint() function from the random package

In [2]:
import random 

def roll(x):
    dict = {'1': 0, '2': 0, '3': 0, '4': 0, '5': 0, '6': 0}
    for i in range(x):
        num = random.randint(1,6)
        num = str(num)
        dict[num] = dict[num] + 1
    return dict

x = input()
print(roll(int(x)))

90
{'1': 7, '2': 17, '3': 8, '4': 17, '5': 21, '6': 20}


### Combine two dictionaries by adding values for common keys.
d1 = {'a': 100, 'b': 200, 'c':300}

d2 = {'a': 300, 'b': 200, 'd':400}

Sample output: {'a': 400, 'b': 400, 'd': 400, 'c': 300}

In [32]:
from collections import Counter

d1 = {'a': 100, 'b': 200, 'c':300}
d2 = {'a': 300, 'b': 200, 'd':400}
X,Y = Counter(d1), Counter(d2)
z = dict(X+Y)
print(z)

{'a': 400, 'b': 400, 'c': 300, 'd': 400}


### Create a list of lists. Then, write a list comprehension that creates a list with the lengths of each (sub)list in the primary list

### Exceptions

Write your own function *my_division* that gets two variables a and b and returns a divided by b. Catch the ZeroDivisionError that occurs if b equals 0 and return 1 in this case.

How could the same behavior be achieved without catching an exception?

In [30]:
a = 42
b = 0
try:
    print(a/b)
except ZeroDivisionError as e:
    print(1)


1


### File handling

Write a function that gets a letter and the path to a (text-)file on your harddrive as input parameters and computes a list as its output. The list should contain one number for each line. The i-th line shows, how often the given letter occurs in line number i.

In [47]:
t = open("test.txt",'r')
txt = t.read()

import collections

txt1 = txt
txt1 = txt1.replace(' ', '')  # 删掉换行符
txt1 = txt1.replace('\n', '')  # 删掉换行符
txt1 = txt1.replace(',', '')  # 删掉逗号
txt1 = txt1.replace('.', '')  # 删掉句号
mylist = list(txt1)
mycount = collections.Counter(mylist)
for key, val in mycount.most_common(10):  # 有序（返回前10个）
    print(key, val)

a 4
d 4
b 3
c 2


### Change please!
In our currency, we have coins with certain values, e.g., (200,100,50,20,10,5,2,1) cents. Write a function that computes the different options to pay a certain amount X with the given set of coins.

## Numpy

### Create a numpy array with 20 rows and 10 columns, where all values are set to zero

In [5]:
import numpy as np
np.zeros((20,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

### Create an array with the same shape containing all natural numbers 0-199

In [11]:
A = np.arange(0,200,1).reshape(20,10)
print(A)

[[  0   1   2   3   4   5   6   7   8   9]
 [ 10  11  12  13  14  15  16  17  18  19]
 [ 20  21  22  23  24  25  26  27  28  29]
 [ 30  31  32  33  34  35  36  37  38  39]
 [ 40  41  42  43  44  45  46  47  48  49]
 [ 50  51  52  53  54  55  56  57  58  59]
 [ 60  61  62  63  64  65  66  67  68  69]
 [ 70  71  72  73  74  75  76  77  78  79]
 [ 80  81  82  83  84  85  86  87  88  89]
 [ 90  91  92  93  94  95  96  97  98  99]
 [100 101 102 103 104 105 106 107 108 109]
 [110 111 112 113 114 115 116 117 118 119]
 [120 121 122 123 124 125 126 127 128 129]
 [130 131 132 133 134 135 136 137 138 139]
 [140 141 142 143 144 145 146 147 148 149]
 [150 151 152 153 154 155 156 157 158 159]
 [160 161 162 163 164 165 166 167 168 169]
 [170 171 172 173 174 175 176 177 178 179]
 [180 181 182 183 184 185 186 187 188 189]
 [190 191 192 193 194 195 196 197 198 199]]


### Create a 4-dimensional array with exactly 16 elements and set all values to a random integer smaller than 5

In [23]:
B = np.random.randint(0,5,(4,4))
print(B)

[[0 4 1 1]
 [1 0 4 2]
 [1 3 1 3]
 [0 3 3 3]]


### What is the mean of all values contained in this array?

In [24]:
np.mean(B)

1.875

### Select a sub-array containing exactly two elements of that array!

In [25]:
B[2,:]

array([1, 3, 1, 3])

### Given a numpy array, return a new numpy array that contains only the elements that are greater than 100

In [26]:
a = np.random.randint(-1000, 1000, (5, 5))
np.maximum(a, 100)

array([[181, 100, 100, 972, 100],
       [219, 403, 265, 252, 196],
       [951, 922, 100, 554, 100],
       [100, 796, 993, 100, 100],
       [100, 100, 859, 134, 100]])